name: koboldcpp
channels:
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cuda-nvcc
  - cuda-libraries-dev
  - cxx-compiler
  - gxx=10
  - pip
  - git
  - clblast
  - ninja
  - make
  - packaging
  - pyinstaller
  - libcblas
  - ocl-icd-system
  - libvulkan-loader
  - tk=*=xft_*
  - pip:
    - customtkinter
